#Requires -Version 5.1
<#
.SYNOPSIS
  Bounded, read-only Codex repository review runner.

.DESCRIPTION
  Exit codes: 0 success, 2 usage/configuration, 3 prerequisite, 4 Codex
  failure, 5 contract failure, 6 timeout, 7 output-size limit.
#>
param(
    [string]$Prompt = 'system-review.md',
    [string]$BaseBranch = '',
    [int]$TimeoutSeconds = 900,
    [int]$MaxOutputBytes = 5242880,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$HarnessRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $HarnessRoot
. (Join-Path $HarnessRoot 'scripts\ci\Review-Helpers.ps1')

function Fail([int]$Code, [string]$Message) { Write-Error $Message; exit $Code }
if ($TimeoutSeconds -lt 1 -or $MaxOutputBytes -lt 1024) { Fail 2 'TimeoutSeconds must be positive and MaxOutputBytes must be at least 1024.' }

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 3 'Git is not installed or not on PATH.' }
if (-not (Get-Command codex -ErrorAction SilentlyContinue)) { Fail 3 'Codex CLI is not installed or not on PATH.' }
$gitTop = git rev-parse --show-toplevel 2>$null
if (-not $gitTop) { Fail 3 'This folder is not inside a Git repository.' }

$configPath = Join-Path $HarnessRoot 'config\review-config.yaml'
if (-not (Test-Path -LiteralPath $configPath)) { Fail 2 "Missing config file: $configPath" }
$configText = Get-Content -LiteralPath $configPath -Raw
function Get-YamlValue([string]$Text, [string]$Key, [string]$Default = '') {
    $match = [regex]::Match($Text, "(?m)^\s*$([regex]::Escape($Key))\s*:\s*[`"']?([^`"'\r\n#]+)")
    if ($match.Success) { return $match.Groups[1].Value.Trim() }
    return $Default
}
$cfgBase = Get-YamlValue $configText 'base_branch' 'main'
$cfgSandbox = Get-YamlValue $configText 'sandbox' 'read-only'
$nestedReport = [regex]::Match($configText, '(?ms)^report:\s*\r?\n(?:\s+#.*\r?\n)*\s+output_dir:\s*[`"'']?([^`"''\r\n#]+)')
$cfgOutDir = if ($nestedReport.Success) { $nestedReport.Groups[1].Value.Trim() } else { 'reports' }
if ($BaseBranch -eq '') { $BaseBranch = $cfgBase }
if ($cfgSandbox -ne 'read-only') { Write-Warning "Config sandbox is '$cfgSandbox'; forcing read-only." }
if ([IO.Path]::IsPathRooted($cfgOutDir) -or $cfgOutDir.Contains('..')) { Fail 2 'report.output_dir must be a repository-relative path.' }

$promptPath = Join-Path $HarnessRoot (Join-Path 'prompts' $Prompt)
if (-not (Test-Path -LiteralPath $promptPath)) { Fail 2 "Prompt file not found: $Prompt" }
$reportsDir = Join-Path $HarnessRoot $cfgOutDir
New-Item -ItemType Directory -Path $reportsDir -Force | Out-Null
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$reportFile = Join-Path $reportsDir "review-$timestamp.md"
$jsonFile = [IO.Path]::ChangeExtension($reportFile, '.json')
$hashFile = [IO.Path]::ChangeExtension($reportFile, '.sha256')

$promptContent = Get-Content -LiteralPath $promptPath -Raw
$fullPrompt = @"
You are running inside the Codex Repo Review Harness. Sandbox mode is forced to read-only.
Do not modify files, access external systems, or claim unverified runtime behavior.
Base branch: $BaseBranch
Follow this trusted prompt exactly:
----- BEGIN PROMPT -----
$promptContent
----- END PROMPT -----
"@
$codexArgs = @('exec', '--sandbox', 'read-only', $fullPrompt)
if ($DryRun) {
    Write-Host "Prepared bounded read-only review; prompt length=$($fullPrompt.Length), timeout=$TimeoutSeconds seconds, max_output_bytes=$MaxOutputBytes."
    exit 0
}

$job = Start-Job -ScriptBlock { param($Args) & codex @Args 2>&1 | Out-String } -ArgumentList (,$codexArgs)
try {
    if (-not (Wait-Job -Job $job -Timeout $TimeoutSeconds)) {
        Stop-Job -Job $job -ErrorAction SilentlyContinue
        Fail 6 "Codex review timed out after $TimeoutSeconds seconds."
    }
    $output = (Receive-Job -Job $job | Out-String)
} finally { Remove-Job -Job $job -Force -ErrorAction SilentlyContinue }
$output = ConvertTo-RedactedText $output
if ([Text.Encoding]::UTF8.GetByteCount($output) -gt $MaxOutputBytes) { Fail 7 "Codex output exceeded $MaxOutputBytes bytes." }

$header = "# Codex Repository Review Report`nGenerated by the Codex Repo Review Harness`n**Timestamp:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n**Base branch:** $BaseBranch`n**Sandbox:** read-only`n**Prompt:** $Prompt`n**Repository:** $gitTop`n`n---`n`n"
$fullReport = $header + $output
Set-Content -LiteralPath $reportFile -Value $fullReport -Encoding UTF8
$report = [ordered]@{
    schema_version = '1.0'; status = 'passed'; summary = $output.Substring(0, [Math]::Min($output.Length, 20000)); findings = @()
    metadata = [ordered]@{ repository = $gitTop; commit = (git rev-parse HEAD); generated_at = (Get-Date).ToUniversalTime().ToString('o'); failure_class = 'none' }
}
Set-Content -LiteralPath $jsonFile -Value ($report | ConvertTo-Json -Depth 8) -Encoding UTF8
Get-FileHash -Algorithm SHA256 $reportFile, $jsonFile | ForEach-Object { '{0}  {1}' -f $_.Hash.ToLowerInvariant(), $_.Path.Substring($reportsDir.Length + 1) } | Set-Content -LiteralPath $hashFile -Encoding ASCII
Write-Host "Review finished. Markdown: $reportFile; JSON: $jsonFile; SHA-256: $hashFile"
exit 0
